name: Deploy PR to dokku

on:
  pull_request:
    types: [opened, synchronize, closed, reopened]
    # types: [opened]

env:
  GITHUB_EVENT_ACTION: "${{ github.event.action }}"

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        if: ${{ env.GITHUB_EVENT_ACTION != 'closed' }}

      - name: create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}
          environment: dokku-preview
          auto_merge: false
          required_contexts: '[]'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: set deployment status to in progress
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: dokku-preview
          # environment_url: ${{ steps.deploy.outputs.url }}
          mediaType: '{"previews": ["flash", "ant-man"]}'
          state: in_progress
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # deploy app
      - name: dokku deploy
        id: deploy
        uses: abulte/dokku-pr-action@HEAD
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: app.etalab.studio
          PROJECT: economie-circulaire
          LINKED_SERVICE: postgres

      - name: set deployment status
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: dokku-preview
          environment_url: ${{ steps.deploy.outputs.url }}
          state: ${{ job.status }}
          mediaType: '{"previews": ["ant-man"]}'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: set deployment failure
        uses: octokit/request-action@v2.x
        if: failure()
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: dokku-preview
          environment_url: ${{ steps.deploy.outputs.url }}
          state: ${{ job.status }}
          mediaType: '{"previews": ["ant-man"]}'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
