name: Deploy PR to dokku

on:
  pull_request:
    # types: [opened, synchronize]
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dokku deploy
      uses: actions/dokku-preview-create-action
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: app.etalab.studio
        PROJECT: economie-circulaire
