name: Deploy PR to dokku

on:
  pull_request:
    types: [opened, synchronize]
    # types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # deploy app
      - uses: actions/checkout@v1
      - name: Dokku deploy
        id: deploy
        uses: ./.github/actions/dokku-preview-create-action
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: app.etalab.studio
          PROJECT: economie-circulaire

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          ref: "${{ github.head_ref }}"
          token: "${{ github.token }}"
          target_url: ${{ steps.deploy.outputs.url }}
          environment: dokku-preview

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: ${{ steps.deploy.outputs.url }}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          # target_url: http://my-app-url.com
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
