name: Deploy PR to dokku

on:
  pull_request:
    # types: [opened, synchronize]
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/dokku-preview-create-action
    - name: Dokku deploy
      uses: vitalyliber/dokku-github-action@57b7fd8b32adfe7924e71123a60a988aa0f62d3f
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: app.etalab.studio
        PROJECT: economie-circulaire
