name: Deploy PR to dokku

on:
  pull_request:
    types: [opened, synchronize]
    # types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}
          environment: dokku-preview
          auto_merge: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: set deployment status to in progress
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: dokku-preview
          # environment_url: ${{ steps.deploy.outputs.url }}
          state: in_progress
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # deploy app
      - name: dokku deploy
        id: deploy
        uses: ./.github/actions/dokku-preview-create-action
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: app.etalab.studio
          PROJECT: economie-circulaire

      - name: set deployment status
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: dokku-preview
          environment_url: ${{ steps.deploy.outputs.url }}
          state: ${{ job.status }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
